require('dotenv').config()
const Container = require('./src/services/container/container.service')
const container = new Container()
container.startContainer()
container.getService('message.service').logMessageSended()